In [ ]:
"""Source : Gilber Strang"""
"""Modified Gram-Schmidt Algorithm"""

for j = 1:n                     %#modified Gram-Schmidt
    
    v = A[:,j]                  %#v begins as column j of the original A
    
    for i = 1:j-1               %#columns q1 and q(j-1) are already settled in Q
        
        R[i,j] = Q[:,i]`*v      %#compute R(ij)=transpose(q[i])*a[j] which is q[i].T*v
        
        v = v - R[i,j]*Q[:,i]   %#subtract the projection (q[i].T*v)q[i]
        
    end                         %#v is now perpendicular to all of q[i],...,q[j-1]
    
    R[j,j] = norm(v)            %# the diagonal entries R[jj] are length
    
    Q[:,j] = v/R[j,j]           %#divide v  by its length to get the next q[j]
    
end                             %#the 'for j = 1:n loop' produces all of q[j]

In [7]:
#Implementation with an example 
import numpy as np

A = np.array([[1,2,3],[-1,0,-3],[0,-2,3]])




3
[ 1 -1  0]
1.4142135623730951


In [23]:
#Implementation with an example 

import numpy as np

A = np.array([[1,2,3],[-1,0,-3],[0,-2,3]])

#Initializing matrix R and Q with zeros
R = np.zeros(shape=(3,3))

Q = np.zeros(shape=(3,3))

# The start of the algorithm

for j in range(0,len(A)):
    
    v = A[:,j]
    
    for i in range(0,j):
        
        R[i,j] = np.dot(Q[:,i].T,v)
        
        v = v - (R[i,j]*Q[:,i])
        
    R[j,j] = np.linalg.norm(v)
    
    Q[:,j] = v/R[j,j]

print("R",R)

print("Q",Q)

R [[ 1.41421356  1.41421356  4.24264069]
 [ 0.          2.44948974 -2.44948974]
 [ 0.          0.          1.73205081]]
Q [[ 0.70710678  0.40824829  0.57735027]
 [-0.70710678  0.40824829  0.57735027]
 [ 0.         -0.81649658  0.57735027]]
